Repository bcgov/nr-silva, pull requests merged in 2024-01, with the labels that each got.

#171 fix(ci): wrong repo name
  .gitignore
  backend/pom.xml
  frontend/openshift.deploy.yml
Labels: bug, github_actions

#172 ci: trigger frontend and backend builds
  backend/Dockerfile
  frontend/Dockerfile
Labels: bug

#179 deps: bump @testing-library/jest-dom for @adobe/css-tools
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#181 ci: rotate through 50 PR numbers for FAM
  .github/workflows/pr-open.yml
  common/openshift.init.yml
Labels: github_actions

#185 fix: PR/ZONE numbers inconsistent
  .github/workflows/pr-close.yml
  README.md
Labels: bug, github_actions

#191 chore(deps): vulnerabilities
  backend/pom.xml
Labels: dependencies

#192 fix: Caddyfile wildcard
  frontend/Caddyfile
Labels: bug

#193 bug: Caddy CSPs
  frontend/Caddyfile
Labels: bug

#194 fix: rotating PR numbers for oc cleanup
  .github/workflows/pr-close.yml
Labels: bug

#209 fix: frontend template corrections
  frontend/openshift.deploy.yml
Labels: bug

#207 bug: leaflet and Caddy CSP
  docker-compose.yml
  frontend/Caddyfile
Labels: bug

#210 fix: add labels to autoscalers for cleanup
  backend/openshift.deploy.yml
  frontend/openshift.deploy.yml
Labels: bug

#211 fix: Caddyfile CSP style-src-elem
  frontend/Caddyfile
Labels: bug

#222 feat: remove all postgres and add oracle
  .github/workflows/merge.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  .gitignore
  backend/Dockerfile
  backend/InstallCert.java
  backend/dockerfile-entrypoint.sh
  backend/openshift.deploy.yml
  backend/pom.xml
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/logback-spring.xml
  backend/startup.sh
  common/openshift.init.yml
  database/Dockerfile
  database/openshift.deploy.yml
  docker-compose.yml
Labels: enhancement

#227 fix(ci): stale images
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
Labels: bug, github_actions

#238 chore(ci): codeQL updates
  .github/workflows/analysis.yml
  .github/workflows/merge.yml
  .github/workflows/pr-open.yml
Labels: bug, github_actions

#239 fix(ci): exclude Oracle-provided file from CodeQL
  .github/workflows/analysis.yml
Labels: github_actions

#240 chore(ci): combine CodeQL jobs and work on unsuccessful exclusion
  .github/workflows/analysis.yml
Labels: bug, github_actions
